# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RouteTracking
                                 A QGIS plugin
 Provides Accessibility and Interoperability analysis of a city
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-12-26
        copyright            : (C) 2023 by Gianmarco Naro
        email                : gianmarco.naro@mail.polimi.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RouteTracking class from file RouteTracking.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #

    from .utils import import_libs
    import_libs()

    from .route_tracking import RouteTracking
    return RouteTracking(iface)
